const now = Date.now();
const hoursAgo = (hours) =>
  new Date(now - hours * 60 * 60 * 1000).toISOString();
const minutesAgo = (minutes) =>
  new Date(now - minutes * 60 * 1000).toISOString();
const daysAgo = (days) =>
  new Date(now - days * 24 * 60 * 60 * 1000).toISOString();

export const personas = [
  {
    id: 'dev',
    title: 'Sviluppo',
    description: 'Per condividere progetti, codice e idee tecniche.',
    color: 'bg-emerald-500',
  },
  {
    id: 'creator',
    title: 'Laboratorio creator',
    description: 'Per contenuti creativi, social e media.',
    color: 'bg-fuchsia-500',
  },
  {
    id: 'deep',
    title: 'Conversazioni profonde',
    description: 'Per riflessioni personali e conversazioni profonde.',
    color: 'bg-sky-500',
  },
  {
    id: 'host',
    title: 'Host accogliente',
    description: 'Per curare rituali e stanze con tono accogliente.',
    color: 'bg-amber-400',
  },
];

export const rooms = [
  {
    id: 'room-dev',
    name: 'Dev Lab',
    description: 'Co-creazione su coding, AI, automazioni e side-project.',
    members: 412,
    isPrivate: false,
    tags: ['coding', 'ai', 'automation'],
    prompts: [
      'Condividi un problema tecnico che ti blocca oggi.',
      'Mostra un WIP di prodotto su cui vuoi feedback veloce.',
      'Quale automazione vorresti costruire questa settimana?',
    ],
    theme: {
      primary: '#34d399',
      secondary: '#10b981',
      glow: 'rgba(16,185,129,0.45)',
      text: '#ecfdf5',
    },
  },
  {
    id: 'room-adult',
    name: 'Creator senza rumore',
    description:
      'Per creator stanchi di feed tossici: community, formati e monetizzazione pulita.',
    members: 233,
    isPrivate: false,
    tags: ['creator', 'community', 'monetization'],
    prompts: [
      'Condividi un formato che vorresti testare con la tua community.',
      'Quale sponsorizzazione ti ha fatto dubitare? Racconta e chiedi feedback.',
      'Scrivi un esperimento per ridurre il rumore nei tuoi canali.',
    ],
    theme: {
      primary: '#f472b6',
      secondary: '#fb7185',
      glow: 'rgba(244,114,182,0.45)',
      text: '#fff1f2',
    },
  },
  {
    id: 'room-mental',
    name: 'Deep Talk',
    description: 'Discussioni lunghe, filosofia, crescita personale.',
    members: 142,
    isPrivate: false,
    tags: ['mindset', 'long-form', 'relazioni'],
    prompts: [
      'Racconta una situazione recente che ti ha fatto riflettere.',
      'Quale abitudine digitale vorresti cambiare e perché?',
      'Condividi un momento in cui ti sei sentito davvero ascoltato.',
    ],
    theme: {
      primary: '#60a5fa',
      secondary: '#a78bfa',
      glow: 'rgba(96,165,250,0.45)',
      text: '#eff6ff',
    },
  },
  {
    id: 'room-afterwork',
    name: 'Creatività dopo il lavoro',
    description:
      'Rituali serali per staccare e tornare creativo dopo l’orario di lavoro.',
    members: 278,
    isPrivate: false,
    tags: ['evening', 'creativity', 'rituali'],
    prompts: [
      'Come stacchi la testa dopo il lavoro? Condividi il tuo rituale.',
      'Qual è una piccola attività creativa che ti riaccende la sera?',
      'Scrivi un ostacolo che ti impedisce di riposare e chiedi un consiglio.',
    ],
    theme: {
      primary: '#f59e0b',
      secondary: '#f97316',
      glow: 'rgba(251,146,60,0.45)',
      text: '#fff7ed',
    },
  },
  {
    id: 'room-side',
    name: 'Side project e idee folli',
    description:
      'Progetti paralleli, hack veloci e prototipi condivisi prima del weekend.',
    members: 364,
    isPrivate: false,
    tags: ['side-project', 'prototype', 'builder'],
    prompts: [
      'Racconta un side project che vuoi sbloccare questa settimana.',
      'Condividi un’idea folle e chiedi feedback in 3 punti.',
      'Qual è il pezzo più noioso del tuo progetto? Chiedi come semplificarlo.',
    ],
    theme: {
      primary: '#a855f7',
      secondary: '#6366f1',
      glow: 'rgba(99,102,241,0.45)',
      text: '#f5f3ff',
    },
  },
  {
    id: 'room-techsafe',
    name: 'Tecnologia senza flame',
    description:
      'Discussioni tech con tono calmo: niente guerre tra stack, solo soluzioni.',
    members: 289,
    isPrivate: false,
    tags: ['tech', 'no-flame', 'prod'],
    prompts: [
      'Porta un problema tecnico reale su cui cerchi una soluzione senza polemiche.',
      'Condividi un confronto tra due stack che hai testato e chiedi pareri pratici.',
      'Quale linea guida usi per tenere i team tech sereni? Mettila in thread.',
    ],
    theme: {
      primary: '#38bdf8',
      secondary: '#0ea5e9',
      glow: 'rgba(14,165,233,0.45)',
      text: '#e0f2fe',
    },
  },
  {
    id: 'room-career',
    name: 'Lavoro, carriera e burnout',
    description:
      'Strategie concrete per lavorare bene senza bruciarsi.',
    members: 320,
    isPrivate: false,
    tags: ['lavoro', 'burnout', 'ritmo'],
    prompts: [
      'Racconta una cosa che ti sta pesando al lavoro in questo periodo.',
      'Qual è la cosa che ti scarica di più le energie ultimamente?',
      'Condividi un piccolo progresso che hai fatto oggi.',
      'Su cosa vorresti un consiglio rapido per alleggerire le giornate?',
    ],
    theme: {
      primary: '#facc15',
      secondary: '#eab308',
      glow: 'rgba(250,204,21,0.45)',
      text: '#fefce8',
    },
  },
  {
    id: 'room-digital',
    name: 'Vivere con meno rumore digitale',
    description: 'Notifiche sotto controllo, feed puliti e tempo offline.',
    members: 298,
    isPrivate: false,
    tags: ['digital-detox', 'minimalismo', 'notifiche'],
    prompts: [
      'Racconta un’abitudine digitale che vuoi cambiare questa settimana.',
      'Qual è il tuo rituale per staccare dal telefono? Condividilo in dettaglio.',
      'Chiedi un consiglio per ridurre le notifiche senza perdere ciò che conta.',
    ],
    theme: {
      primary: '#06b6d4',
      secondary: '#0ea5e9',
      glow: 'rgba(6,182,212,0.45)',
      text: '#ecfeff',
    },
  },
  {
    id: 'room-relations',
    name: 'Relazioni e vita adulta',
    description:
      'Confronti su coppia, amicizie e convivenza con tono adulto.',
    members: 185,
    isPrivate: true,
    tags: ['relazioni', 'adulting', 'cura'],
    prompts: [
      'Racconta un momento di convivenza che ti ha messo alla prova.',
      'Condividi un dubbio su amicizie adulte e chiedi come gestirlo.',
      'Scrivi un patto o una regola di casa che funziona per te.',
    ],
    theme: {
      primary: '#fb7185',
      secondary: '#f472b6',
      glow: 'rgba(251,113,133,0.45)',
      text: '#fff1f2',
    },
  },
];

const threadData = [
  {
    id: 'thread-1',
    roomId: 'room-dev',
    title:
      'Costruiamo un tool per migliorare la produttività in magazzino',
    author: 'Pionio-dev',
    personaId: 'dev',
    createdAt: hoursAgo(34),
    depth: 3,
    energy: 'costruttivo',
    rootSnippet:
      'Vorrei un sistema per unire SAP, file Excel e dashboard interattive…',
    branches: 7,
    posts: [
      {
        id: 't1-root',
        parentId: null,
        author: 'Pionio-dev',
        personaId: 'dev',
        createdAt: hoursAgo(34),
        content:
          'Vorrei un flusso da SAP a dashboard leggibile: ingest dei dati grezzi, normalizzazione, alert e viste per operatori.',
        waveCount: 6,
        hasWaved: false,
      },
      {
        id: 't1-r1',
        parentId: 't1-root',
        author: 'Arianna',
        personaId: 'dev',
        createdAt: hoursAgo(31),
        content:
          'Possiamo partire da un layer di eventi: scanner → coda → normalizzatore. Così aggiungiamo simulatore occupancy senza toccare SAP.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't1-r2',
        parentId: 't1-root',
        author: 'Michele',
        personaId: 'dev',
        createdAt: hoursAgo(28),
        content:
          'Per la dashboard userei Grafana con viste per turno. KPI: lead time missioni, pick error rate, saturazione baie.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't1-r3',
        parentId: 't1-r2',
        author: 'Pionio-dev',
        personaId: 'dev',
        createdAt: hoursAgo(26),
        content:
          'Ok, se teniamo i dati in un lake S3 + parquet possiamo fare query veloci anche per audit.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't1-r4',
        parentId: 't1-root',
        author: 'Chiara',
        personaId: 'creator',
        createdAt: hoursAgo(20),
        content:
          'Da ex ops manager: serve un “semaforo” per priorità e blocchi. Il resto può arrivare dopo.',
        waveCount: 5,
        hasWaved: false,
      },
      {
        id: 't1-r5',
        parentId: 't1-r4',
        author: 'Luca',
        personaId: 'dev',
        createdAt: hoursAgo(12),
        content:
          'Metto un mock di layout: card per area, grafico linee, alert in alto. Se vi torna procedo in React.',
        waveCount: 4,
        hasWaved: false,
        attachments: [
          {
            type: 'image',
            url: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=60',
            name: 'mock-dashboard',
          },
        ],
      },
      {
        id: 't1-r6',
        parentId: 't1-r4',
        author: 'Arianna',
        personaId: 'dev',
        createdAt: hoursAgo(8),
        content:
          'Layout ok. Farei slot “suggerimenti AI” con azioni veloci: riequilibra missioni, segnala stock-out.',
        waveCount: 3,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-2',
    roomId: 'room-mental',
    title: 'Come evitare di farsi mangiare dai social',
    author: 'Pionio-thinker',
    personaId: 'deep',
    createdAt: hoursAgo(28),
    depth: 4,
    energy: 'riflessivo',
    rootSnippet:
      'Pensavo a un algoritmo che puoi controllare tu, invece che il contrario…',
    branches: 6,
    posts: [
      {
        id: 't2-root',
        parentId: null,
        author: 'Pionio-thinker',
        personaId: 'deep',
        createdAt: hoursAgo(28),
        content:
          'Se potessi spostare slider tipo % contenuti che mi sfidano vs % comfort cambierebbe tutto. Per ora sto eliminando app dal telefono dopo le 22.',
        waveCount: 5,
        hasWaved: false,
      },
      {
        id: 't2-r1',
        parentId: 't2-root',
        author: 'Irene',
        personaId: 'deep',
        createdAt: hoursAgo(25),
        content:
          'Ho impostato 2 sessioni da 15 minuti al giorno e tolto le app dalla home. Il craving cala dopo 3 giorni.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't2-r2',
        parentId: 't2-root',
        author: 'Ste',
        personaId: 'dev',
        createdAt: hoursAgo(22),
        content:
          'Uso un profilo “lento” su un telefono vecchio: solo browser e niente push. È brutto, quindi lo uso poco.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't2-r3',
        parentId: 't2-r2',
        author: 'Pionio-thinker',
        personaId: 'deep',
        createdAt: hoursAgo(19),
        content:
          'Interessante il telefono brutto. Forse CoWave dovrebbe avere un “modo sessione” di default.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't2-r4',
        parentId: 't2-root',
        author: 'Laura',
        personaId: 'host',
        createdAt: hoursAgo(14),
        content:
          'Ho cambiato le regole della sera: libri in cucina, telefono in corridoio. Non perfetto, ma addormentarsi è più facile.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't2-r5',
        parentId: 't2-r4',
        author: 'Irene',
        personaId: 'deep',
        createdAt: hoursAgo(9),
        content:
          'Per me è stato decisivo disattivare le notifiche “consigliate”. Restano solo gli sms.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-3',
    roomId: 'room-dev',
    title: 'Automatizzare i report per il team support',
    author: 'Nadia',
    personaId: 'dev',
    createdAt: hoursAgo(22),
    depth: 2,
    energy: 'tecnico',
    rootSnippet:
      'Sto rifacendo i report giornalieri del support: meno copy-paste e più alert automatici.',
    branches: 6,
    posts: [
      {
        id: 't3-root',
        parentId: null,
        author: 'Nadia',
        personaId: 'dev',
        createdAt: hoursAgo(22),
        content:
          'Sto rifacendo i report giornalieri del support. Vorrei automatizzare CSAT, ticket riassegnati e tempi di risposta senza dover copiare dati da tre tool.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't3-r1',
        parentId: 't3-root',
        author: 'Marco',
        personaId: 'dev',
        createdAt: hoursAgo(20),
        content:
          'Metti tutto in un db intermedio (Postgres). Ingest via webhook + cron, poi esporti via Metabase.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't3-r2',
        parentId: 't3-root',
        author: 'Sara',
        personaId: 'creator',
        createdAt: hoursAgo(17),
        content:
          'Aggiungi un alert “ticket in attesa > 24h” su Slack. Riduce più di un dashboard che nessuno apre.',
        waveCount: 5,
        hasWaved: false,
      },
      {
        id: 't3-r3',
        parentId: 't3-r1',
        author: 'Nadia',
        personaId: 'dev',
        createdAt: hoursAgo(14),
        content:
          'Postgres ok. Per l’ingest sto usando Airbyte self hosted, così posso agganciare Zendesk e Sheets.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't3-r4',
        parentId: 't3-root',
        author: 'Elia',
        personaId: 'dev',
        createdAt: hoursAgo(10),
        content:
          'Metti anche “casi riaperti” come metrica. È l’unica che ha convinto il management.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't3-r5',
        parentId: 't3-r4',
        author: 'Sara',
        personaId: 'creator',
        createdAt: hoursAgo(6),
        content:
          'True. E fai il confronto settimanale con sparkline, occupa poco spazio e rende chiara la tendenza.',
        waveCount: 3,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-4',
    roomId: 'room-dev',
    title: 'Agenti AI per QA manuale',
    author: 'Lorenzo',
    personaId: 'dev',
    createdAt: hoursAgo(16),
    depth: 2,
    energy: 'tecnico',
    rootSnippet:
      'Sto testando agenti AI per leggere log e ticket e suggerire casi di test.',
    branches: 5,
    posts: [
      {
        id: 't4-root',
        parentId: null,
        author: 'Lorenzo',
        personaId: 'dev',
        createdAt: hoursAgo(16),
        content:
          'Sto testando agenti AI per leggere log, changelog e ticket e generare casi di test. Obiettivo: ridurre il QA manuale ripetitivo.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't4-r1',
        parentId: 't4-root',
        author: 'Giulia',
        personaId: 'dev',
        createdAt: hoursAgo(14),
        content:
          'Fai ingestion su Pinecone con embedding di log + expected behavior. L’agente propone i casi con priorità.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't4-r2',
        parentId: 't4-root',
        author: 'Matteo',
        personaId: 'dev',
        createdAt: hoursAgo(11),
        content:
          'Occhio a non overfit: limita agli ultimi 30 deploy. Altrimenti suggerisce bug già risolti.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't4-r3',
        parentId: 't4-r2',
        author: 'Lorenzo',
        personaId: 'dev',
        createdAt: hoursAgo(9),
        content:
          'Yes, sto taggando per release. Penso di loggare i falsi positivi per riallenare i prompt.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't4-r4',
        parentId: 't4-root',
        author: 'Elena',
        personaId: 'creator',
        createdAt: hoursAgo(7),
        content:
          'Aggiungi un check umano obbligatorio sulle regressioni critiche. Se tutto passa, manda report Slack.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't4-r5',
        parentId: 't4-r4',
        author: 'Giulia',
        personaId: 'dev',
        createdAt: hoursAgo(5),
        content:
          'Se vuoi loggare esiti, usa un form interno con toggle “ho provato” per non falsare i dati.',
        waveCount: 1,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-5',
    roomId: 'room-adult',
    title: 'Newsletter privata al posto dell’ennesimo reel',
    author: 'Vale',
    personaId: 'creator',
    createdAt: hoursAgo(20),
    depth: 2,
    energy: 'costruttivo',
    rootSnippet:
      'Sto testando una newsletter chiusa al posto dei reel: stesso effort, meno rumore.',
    branches: 6,
    posts: [
      {
        id: 't5-root',
        parentId: null,
        author: 'Vale',
        personaId: 'creator',
        createdAt: hoursAgo(20),
        content:
          'Sto testando una newsletter chiusa su Buttondown al posto dell’ennesimo reel. Voglio vedere se 8 post curati battono 40 storie rumorose.',
        waveCount: 5,
        hasWaved: false,
      },
      {
        id: 't5-r1',
        parentId: 't5-root',
        author: 'Ludo',
        personaId: 'creator',
        createdAt: hoursAgo(18),
        content:
          'Fai drip di 4 mail con CTA verso un canale Telegram piccolo. Così misuri retention senza feed.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't5-r2',
        parentId: 't5-root',
        author: 'Enzo',
        personaId: 'dev',
        createdAt: hoursAgo(16),
        content:
          'Per i pagamenti usa LemonSqueezy + tag. Io ho messo “supporter” e “clienti” e mando contenuti diversi.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't5-r3',
        parentId: 't5-r1',
        author: 'Vale',
        personaId: 'creator',
        createdAt: hoursAgo(14),
        content:
          'Interessante. Così evito l’algoritmo IG e porto chi vuole davvero seguire.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't5-r4',
        parentId: 't5-root',
        author: 'Giada',
        personaId: 'creator',
        createdAt: hoursAgo(9),
        content:
          'Tieni un reel ogni tanto solo per top-of-funnel e invita alla lista. Il resto lo togli senza sensi di colpa.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't5-r5',
        parentId: 't5-r4',
        author: 'Vale',
        personaId: 'creator',
        createdAt: hoursAgo(6),
        content:
          'Sì, sto lasciando solo highlight mensili. I commenti tossici sono scesi quasi a zero.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-6',
    roomId: 'room-adult',
    title: 'Community chiusa: cosa mostrate davvero?',
    author: 'Marta',
    personaId: 'host',
    createdAt: hoursAgo(14),
    depth: 2,
    energy: 'riflessivo',
    rootSnippet:
      'Sto aprendo una community chiusa: cosa mostrare dentro che non sia la copia di Instagram?',
    branches: 5,
    posts: [
      {
        id: 't6-root',
        parentId: null,
        author: 'Marta',
        personaId: 'host',
        createdAt: hoursAgo(14),
        content:
          'Sto aprendo una community chiusa per i miei corsi. Voglio che abbia senso pagarla: niente copia di IG, ma materiali utili e spazio senza spam.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't6-r1',
        parentId: 't6-root',
        author: 'Rico',
        personaId: 'creator',
        createdAt: hoursAgo(12),
        content:
          'Io mostro WIP e dietro le quinte. La gente paga per vedere processi, non solo output.',
        waveCount: 5,
        hasWaved: false,
      },
      {
        id: 't6-r2',
        parentId: 't6-root',
        author: 'Elena',
        personaId: 'deep',
        createdAt: hoursAgo(11),
        content:
          'Fai office hour settimanale con 5 posti. Bassa scala ma altissima percezione di cura.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't6-r3',
        parentId: 't6-r1',
        author: 'Marta',
        personaId: 'host',
        createdAt: hoursAgo(9),
        content:
          'Mi piace il WIP. Potrei fare check-list scaricabili e link agli strumenti.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't6-r4',
        parentId: 't6-root',
        author: 'Stefano',
        personaId: 'creator',
        createdAt: hoursAgo(7),
        content:
          'Evita role di moderatori casuali. Meglio 1-2 host chiari e regole visibili in alto.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't6-r5',
        parentId: 't6-r4',
        author: 'Elena',
        personaId: 'deep',
        createdAt: hoursAgo(5),
        content:
          '+1. Scrivi il patto della stanza: ritmo, tono, cosa non si fa. Riduce drammi.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-7',
    roomId: 'room-adult',
    title: 'Sponsorship che non puzzano di marchetta',
    author: 'Andrea',
    personaId: 'creator',
    createdAt: hoursAgo(10),
    depth: 2,
    energy: 'costruttivo',
    rootSnippet:
      'Sto cercando sponsor che non rovinino il rapporto con la community: come filtrate?',
    branches: 5,
    posts: [
      {
        id: 't7-root',
        parentId: null,
        author: 'Andrea',
        personaId: 'creator',
        createdAt: hoursAgo(10),
        content:
          'Sto cercando sponsor per il podcast ma non voglio l’effetto marchetta. Come filtrate brand e come dichiarate cosa è sponsorizzato?',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't7-r1',
        parentId: 't7-root',
        author: 'Giulia',
        personaId: 'host',
        createdAt: hoursAgo(9),
        content:
          'Chiedo 3 cose: uso reale del prodotto, clausola editoriale e diritto di rifiutare claim. Se non accettano, passo.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't7-r2',
        parentId: 't7-root',
        author: 'Leo',
        personaId: 'creator',
        createdAt: hoursAgo(8),
        content:
          'Metti “episodio sostenuto da X, opinioni mie” all’inizio. La community lo apprezza più della disclosure minuscola.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't7-r3',
        parentId: 't7-root',
        author: 'Vale',
        personaId: 'creator',
        createdAt: hoursAgo(7),
        content:
          'Paga in tempo? È già filtro. E fai slot limitati al mese per non saturare.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't7-r4',
        parentId: 't7-r1',
        author: 'Andrea',
        personaId: 'creator',
        createdAt: hoursAgo(6),
        content:
          'Inserirò la clausola editoriale nel contratto. Temevo fosse troppo, ma ha senso.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't7-r5',
        parentId: 't7-root',
        author: 'Sofia',
        personaId: 'deep',
        createdAt: hoursAgo(4),
        content:
          'Rendi pubbliche le linee guida sponsor. Così chi ascolta sa che hai un filtro e si fida di più.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-8',
    roomId: 'room-mental',
    title: 'Parlare di solitudine senza pietismo',
    author: 'Michela',
    personaId: 'deep',
    createdAt: hoursAgo(18),
    depth: 3,
    energy: 'riflessivo',
    rootSnippet:
      'Vorrei discutere di solitudine in modo pratico, non solo post motivazionali.',
    branches: 5,
    posts: [
      {
        id: 't8-root',
        parentId: null,
        author: 'Michela',
        personaId: 'deep',
        createdAt: hoursAgo(18),
        content:
          'Vorrei parlare di solitudine senza pietismo. Cose pratiche: come costruite legami nuovi senza sentirvi strani?',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't8-r1',
        parentId: 't8-root',
        author: 'Rami',
        personaId: 'host',
        createdAt: hoursAgo(16),
        content:
          'Ho iniziato con micro-inviti: caffè di 20 minuti dopo palestra. È meno impegnativo e si ripete più facile.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't8-r2',
        parentId: 't8-root',
        author: 'Elisa',
        personaId: 'deep',
        createdAt: hoursAgo(14),
        content:
          'Mi ha aiutato un gruppo di lettura. Ritmo mensile, 6 persone fisse, regola “niente consigli non richiesti”.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't8-r3',
        parentId: 't8-root',
        author: 'Tommaso',
        personaId: 'creator',
        createdAt: hoursAgo(11),
        content:
          'Uso un foglio “chi voglio sentire questa settimana”. Sembra freddo, ma mi impedisce di sparire per mesi.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't8-r4',
        parentId: 't8-r2',
        author: 'Michela',
        personaId: 'deep',
        createdAt: hoursAgo(9),
        content: 'Il gruppo lettura suona fattibile. Condividi come scegliete i libri?',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't8-r5',
        parentId: 't8-root',
        author: 'Rami',
        personaId: 'host',
        createdAt: hoursAgo(7),
        content:
          'Io ho messo un “segnale” nel profilo: disponibile per coworking silenzioso. Sorprendentemente funziona.',
        waveCount: 3,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-9',
    roomId: 'room-mental',
    title: 'Routine del mattino per non partire in rincorsa',
    author: 'Luna',
    personaId: 'host',
    createdAt: hoursAgo(8),
    depth: 2,
    energy: 'costruttivo',
    rootSnippet:
      'Sto cercando una routine mattutina breve: 20 minuti realistici che non saltino dopo due giorni.',
    branches: 5,
    posts: [
      {
        id: 't9-root',
        parentId: null,
        author: 'Luna',
        personaId: 'host',
        createdAt: hoursAgo(8),
        content:
          'Sto cercando una routine mattutina breve: 20 minuti realistici, niente audio di 1h. Cosa vi fa iniziare la giornata senza rincorrere notifiche?',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't9-r1',
        parentId: 't9-root',
        author: 'Paolo',
        personaId: 'deep',
        createdAt: hoursAgo(7),
        content:
          '3 cose: luce naturale alla finestra, acqua con sale, lista di 3 compiti. Finisce tutto in 12 minuti.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't9-r2',
        parentId: 't9-root',
        author: 'Giada',
        personaId: 'creator',
        createdAt: hoursAgo(6),
        content:
          'Metto le cuffie senza musica per 5 minuti e respiro. Sembra poco, ma mi stacca dal telefono.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't9-r3',
        parentId: 't9-root',
        author: 'Luca',
        personaId: 'dev',
        createdAt: hoursAgo(5),
        content:
          'Io preparo la colazione la sera. Così la mattina non devo decidere nulla e resto offline fino alle 9.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't9-r4',
        parentId: 't9-r3',
        author: 'Luna',
        personaId: 'host',
        createdAt: hoursAgo(4),
        content: 'Ok, preparo la moka la sera. Mi toglie un pensiero.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't9-r5',
        parentId: 't9-root',
        author: 'Sara',
        personaId: 'deep',
        createdAt: hoursAgo(3),
        content:
          'Tengo un “primo feed” cartaceo: appunti e 5 righe di diario. Mi impedisce di aprire il telefono appena sveglia.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-10',
    roomId: 'room-afterwork',
    title: 'Come staccate la testa dopo il turno?',
    author: 'Teo',
    personaId: 'host',
    createdAt: hoursAgo(18),
    depth: 3,
    energy: 'riflessivo',
    rootSnippet:
      'Sto provando un rituale di 30 minuti per chiudere la giornata e non portarmi il lavoro a casa.',
    branches: 6,
    posts: [
      {
        id: 't10-root',
        parentId: null,
        author: 'Teo',
        personaId: 'host',
        createdAt: hoursAgo(18),
        content:
          'Sto provando un rituale di 30 minuti dopo il turno: camminata + diario rapido. Cosa vi fa spegnere davvero?',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't10-r1',
        parentId: 't10-root',
        author: 'Marta',
        personaId: 'deep',
        createdAt: hoursAgo(16),
        content:
          'Doccia calda + vestiti comodi appena arrivo. Segnale forte che la giornata è chiusa.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't10-r2',
        parentId: 't10-root',
        author: 'Diego',
        personaId: 'dev',
        createdAt: hoursAgo(15),
        content:
          '10 min di stretching schiena e niente telefono fino a cena. Le notifiche dopo mandano in tilt.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't10-r3',
        parentId: 't10-r2',
        author: 'Teo',
        personaId: 'host',
        createdAt: hoursAgo(13),
        content:
          'Confermo: se apro il telefono entro in loop. Timer da cucina a 25 min e lo rispetti.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't10-r4',
        parentId: 't10-root',
        author: 'Elisa',
        personaId: 'creator',
        createdAt: hoursAgo(9),
        content:
          'Ho iniziato a fare collage su carta. Mani occupate, cervello libero. Bastano 15 minuti.',
        waveCount: 4,
        hasWaved: false,
        attachments: [
          {
            type: 'image',
            url: 'https://images.unsplash.com/photo-1523419400524-221c8238c004?auto=format&fit=crop&w=1200&q=60',
            name: 'collage-notebook',
          },
        ],
      },
      {
        id: 't10-r5',
        parentId: 't10-r4',
        author: 'Diego',
        personaId: 'dev',
        createdAt: hoursAgo(7),
        content: 'Che materiali usi? Devo provare qualcosa di tattile.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't10-r6',
        parentId: 't10-r5',
        author: 'Elisa',
        personaId: 'creator',
        createdAt: hoursAgo(5),
        content:
          'Ritagli di riviste e penna gel. Costa zero e mi impedisce di aprire le app.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-11',
    roomId: 'room-afterwork',
    title: 'Serate analogiche con amici',
    author: 'Giulia',
    personaId: 'host',
    createdAt: hoursAgo(12),
    depth: 2,
    energy: 'giocoso',
    rootSnippet:
      'Vorrei organizzare serate senza schermi: idee semplici che non richiedano logistica.',
    branches: 5,
    posts: [
      {
        id: 't11-root',
        parentId: null,
        author: 'Giulia',
        personaId: 'host',
        createdAt: hoursAgo(12),
        content:
          'Sto provando a fare serate analogiche. Giochi semplici, chiacchiere, niente tv. Idee low effort?',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't11-r1',
        parentId: 't11-root',
        author: 'Andrea',
        personaId: 'creator',
        createdAt: hoursAgo(11),
        content:
          'Porta un mazzo di carte e un tema: “cose che abbiamo imparato tardi”. Parte sempre.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't11-r2',
        parentId: 't11-root',
        author: 'Vale',
        personaId: 'deep',
        createdAt: hoursAgo(10),
        content:
          'Facciamo “walk and talk” dopo cena. Giro da 20 minuti, poi tisana. Telefoni in tasca.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't11-r3',
        parentId: 't11-root',
        author: 'Luca',
        personaId: 'dev',
        createdAt: hoursAgo(9),
        content:
          'Io porto un proiettore ma solo per guardare foto tra amici e commentarle. È più conviviale di Netflix.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't11-r4',
        parentId: 't11-r1',
        author: 'Giulia',
        personaId: 'host',
        createdAt: hoursAgo(7),
        content:
          'Mi piace il tema fisso. Potrei scrivere le domande su bigliettini.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't11-r5',
        parentId: 't11-root',
        author: 'Elena',
        personaId: 'host',
        createdAt: hoursAgo(5),
        content:
          'Piccolo laboratorio di pasta fatta in casa. Impasta una persona, gli altri chiacchierano e aiutano.',
        waveCount: 3,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-12',
    roomId: 'room-afterwork',
    title: 'Allenamento leggero post ufficio',
    author: 'Raf',
    personaId: 'dev',
    createdAt: hoursAgo(6),
    depth: 2,
    energy: 'costruttivo',
    rootSnippet:
      'Cerco routine di movimento di 20 minuti dopo l’ufficio che non richiedano palestra.',
    branches: 5,
    posts: [
      {
        id: 't12-root',
        parentId: null,
        author: 'Raf',
        personaId: 'dev',
        createdAt: hoursAgo(6),
        content:
          'Cerco una routine di movimento da 20 minuti post ufficio senza andare in palestra. Stretching o kettlebell leggero?',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't12-r1',
        parentId: 't12-root',
        author: 'Mara',
        personaId: 'host',
        createdAt: hoursAgo(5),
        content:
          'Prova EMOM con 3 esercizi: goblet squat, plank, rematore. 6 round e hai finito.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't12-r2',
        parentId: 't12-root',
        author: 'Diego',
        personaId: 'dev',
        createdAt: hoursAgo(4),
        content:
          'Io metto il tappetino in salotto appena entro. Zero frizioni. Faccio 10 minuti di mobilità anche se sono stanco.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't12-r3',
        parentId: 't12-r2',
        author: 'Raf',
        personaId: 'dev',
        createdAt: hoursAgo(3),
        content: 'Mettere il tappetino subito mi pare la mossa. Così evito il divano.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't12-r4',
        parentId: 't12-root',
        author: 'Chiara',
        personaId: 'deep',
        createdAt: minutesAgo(90),
        content:
          'Se fai EMOM chiudi in 18 minuti. Aggiungi 2 minuti di respirazione nasale alla fine e dormi meglio.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't12-r5',
        parentId: 't12-r1',
        author: 'Mara',
        personaId: 'host',
        createdAt: minutesAgo(40),
        content:
          'Metti un timer visivo grande. Non serve musica, basta non controllare il telefono.',
        waveCount: 1,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-13',
    roomId: 'room-side',
    title: 'Racconta un progetto che non hai mai finito',
    author: 'Ale',
    personaId: 'creator',
    createdAt: hoursAgo(26),
    depth: 3,
    energy: 'riflessivo',
    rootSnippet:
      'Qual è un side project fermo nel cassetto? Perché? Vorrei capire dove ci blocchiamo.',
    branches: 6,
    posts: [
      {
        id: 't13-root',
        parentId: null,
        author: 'Ale',
        personaId: 'creator',
        createdAt: hoursAgo(26),
        content:
          'Qual è un side project fermo nel cassetto? Perché si è fermato? Vorrei capire dove ci blocchiamo.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't13-r1',
        parentId: 't13-root',
        author: 'Fede',
        personaId: 'dev',
        createdAt: hoursAgo(24),
        content:
          'App per mappare fontanelle in città. Bloccato su design e offline. Forse bastava un pdf.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't13-r2',
        parentId: 't13-root',
        author: 'Luisa',
        personaId: 'host',
        createdAt: hoursAgo(22),
        content:
          'Newsletter sulle micro-routine. Ho mollato quando ho provato a farla settimanale. Ritmo impossibile.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't13-r3',
        parentId: 't13-r2',
        author: 'Ale',
        personaId: 'creator',
        createdAt: hoursAgo(19),
        content:
          'Se la porti a quindicinale? O blocchi da 4 mail e poi pausa.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't13-r4',
        parentId: 't13-root',
        author: 'Gian',
        personaId: 'dev',
        createdAt: hoursAgo(15),
        content:
          'Plugin per Figma per generare moodboard. Mi ha fermato la parte di auth, ora sto valutando login magic link.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't13-r5',
        parentId: 't13-r4',
        author: 'Fede',
        personaId: 'dev',
        createdAt: hoursAgo(9),
        content:
          'Se vuoi testare senza auth metti un limite di export e salva local. Così sblocchi feedback.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't13-r6',
        parentId: 't13-root',
        author: 'Sara',
        personaId: 'deep',
        createdAt: hoursAgo(6),
        content:
          'Mi blocco quando penso al “lanciarlo”. Forse dovremmo condividere versioni brutte ogni settimana.',
        waveCount: 4,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-14',
    roomId: 'room-side',
    title: 'Pitch del weekend in 48h',
    author: 'Gio',
    personaId: 'dev',
    createdAt: hoursAgo(20),
    depth: 2,
    energy: 'giocoso',
    rootSnippet:
      'Propongo una challenge: 48h per un pitch decente di un’idea. Strumenti, regole?',
    branches: 5,
    posts: [
      {
        id: 't14-root',
        parentId: null,
        author: 'Gio',
        personaId: 'dev',
        createdAt: hoursAgo(20),
        content:
          'Propongo challenge: 48h per un pitch decente di un’idea. Niente prodotto, solo demo clickable. Ci state?',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't14-r1',
        parentId: 't14-root',
        author: 'Mimi',
        personaId: 'creator',
        createdAt: hoursAgo(18),
        content:
          'Mettiamo regole: deck da 6 slide max, demo Figma/Slides, video di 90 secondi.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't14-r2',
        parentId: 't14-root',
        author: 'Raf',
        personaId: 'dev',
        createdAt: hoursAgo(16),
        content:
          'Serve un template: problema, insight, soluzione, call to action. Così non diventiamo una hackathon infinita.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't14-r3',
        parentId: 't14-r2',
        author: 'Gio',
        personaId: 'dev',
        createdAt: hoursAgo(14),
        content: 'Template ottimo. Io preparo una board Notion con check-box.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't14-r4',
        parentId: 't14-root',
        author: 'Lia',
        personaId: 'deep',
        createdAt: hoursAgo(11),
        content:
          'Premio: feedback sincero da 3 persone diverse (dev, designer, host). Basta quello per motivare.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't14-r5',
        parentId: 't14-r4',
        author: 'Mimi',
        personaId: 'creator',
        createdAt: hoursAgo(8),
        content:
          'Facciamo retro lunedì: cosa è rimasto in piedi e cosa no.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-15',
    roomId: 'room-side',
    title: 'Collabo lampo: chi porta cosa',
    author: 'Silvia',
    personaId: 'host',
    createdAt: hoursAgo(7),
    depth: 2,
    energy: 'costruttivo',
    rootSnippet:
      'Mi servono collabo di 2 settimane max: chi porta prodotto, chi porta audience, chi porta design?',
    branches: 5,
    posts: [
      {
        id: 't15-root',
        parentId: null,
        author: 'Silvia',
        personaId: 'host',
        createdAt: hoursAgo(7),
        content:
          'Mi servono collabo lampo (2 settimane max). Chi porta prodotto, chi porta audience, chi porta design? Cerco schema per capirlo subito.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't15-r1',
        parentId: 't15-root',
        author: 'Pietro',
        personaId: 'dev',
        createdAt: hoursAgo(6),
        content:
          'Io porto dev veloce. Mi serve qualcuno che validi con 10 utenti in 3 giorni. Se non succede, stop.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't15-r2',
        parentId: 't15-root',
        author: 'Lia',
        personaId: 'creator',
        createdAt: hoursAgo(5),
        content:
          'Porto 4k iscritti newsletter e design. Non prometto vendite, ma 50 risposte al sondaggio sì.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't15-r3',
        parentId: 't15-r2',
        author: 'Silvia',
        personaId: 'host',
        createdAt: hoursAgo(4),
        content:
          'Perfetto. Facciamo una lista di check-in: giorno 3 demo, giorno 10 landing + CTA.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't15-r4',
        parentId: 't15-root',
        author: 'Gian',
        personaId: 'dev',
        createdAt: hoursAgo(3),
        content:
          'Propongo accordo scritto di 1 pagina: scope, tempo, ownership. Evita drammi finali.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't15-r5',
        parentId: 't15-r4',
        author: 'Lia',
        personaId: 'creator',
        createdAt: minutesAgo(50),
        content:
          'Yes, e mettiamo clausola “pubblico cosa ho imparato” così restano tracce.',
        waveCount: 1,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-16',
    roomId: 'room-techsafe',
    title: 'Stack minimo per app mobile tranquilla',
    author: 'Davide',
    personaId: 'dev',
    createdAt: hoursAgo(30),
    depth: 2,
    energy: 'tecnico',
    rootSnippet:
      'Serve uno stack mobile senza flame: cosa usare per login, push e analytics senza vendor lock?',
    branches: 5,
    posts: [
      {
        id: 't16-root',
        parentId: null,
        author: 'Davide',
        personaId: 'dev',
        createdAt: hoursAgo(30),
        content:
          'Cerco stack mobile senza flame: login, push e analytics senza vendor lock. Voglio dormire la notte.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't16-r1',
        parentId: 't16-root',
        author: 'Anna',
        personaId: 'dev',
        createdAt: hoursAgo(28),
        content:
          'Expo + Supabase: auth, db e storage già pronti. Push con Expo push service e via.',
        waveCount: 5,
        hasWaved: false,
      },
      {
        id: 't16-r2',
        parentId: 't16-root',
        author: 'Luca',
        personaId: 'dev',
        createdAt: hoursAgo(25),
        content:
          'Se vuoi ridurre lock usa Clerk per auth e Posthog per analytics. Entrambi esportano dati.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't16-r3',
        parentId: 't16-r2',
        author: 'Davide',
        personaId: 'dev',
        createdAt: hoursAgo(22),
        content: 'Posthog mi ispira. Voglio evitare mixpanel per costi.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't16-r4',
        parentId: 't16-root',
        author: 'Sara',
        personaId: 'creator',
        createdAt: hoursAgo(18),
        content:
          'Metti feature flag fin da subito. Plausible per analytics privacy-first può bastare.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't16-r5',
        parentId: 't16-r4',
        author: 'Anna',
        personaId: 'dev',
        createdAt: hoursAgo(15),
        content: 'Concordo sui flag. Usa ConfigCat free tier per iniziare.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-17',
    roomId: 'room-techsafe',
    title: 'AI sì/no: cosa usate davvero',
    author: 'Nico',
    personaId: 'dev',
    createdAt: hoursAgo(15),
    depth: 2,
    energy: 'riflessivo',
    rootSnippet:
      'Curioso su quanto AI usate per lavoro reale e quanto hype. Tool concreti?',
    branches: 5,
    posts: [
      {
        id: 't17-root',
        parentId: null,
        author: 'Nico',
        personaId: 'dev',
        createdAt: hoursAgo(15),
        content:
          'Quanta AI usate davvero in produzione? Tool concreti, niente flame. Io uso solo Copilot e un servizio di trascrizione.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't17-r1',
        parentId: 't17-root',
        author: 'Bea',
        personaId: 'deep',
        createdAt: hoursAgo(14),
        content:
          'Copilot per refactoring e Whisper per note vocali. Ho smesso con gli agenti autonomi: troppo rumorosi.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't17-r2',
        parentId: 't17-root',
        author: 'Luca',
        personaId: 'dev',
        createdAt: hoursAgo(12),
        content:
          'Per i dati usiamo GPT per generare query di test e validazione schema. Nessun agente in prod.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't17-r3',
        parentId: 't17-r2',
        author: 'Nico',
        personaId: 'dev',
        createdAt: hoursAgo(10),
        content: 'Interessante sulle query. Fate review umana sempre?',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't17-r4',
        parentId: 't17-root',
        author: 'Marta',
        personaId: 'creator',
        createdAt: hoursAgo(9),
        content:
          'Uso Midjourney solo per moodboard di clienti. Mai consegna finale. Evita discussioni infinite.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't17-r5',
        parentId: 't17-r1',
        author: 'Bea',
        personaId: 'deep',
        createdAt: hoursAgo(7),
        content:
          'Copilot va bene solo se ho scritto io la funzione. Altrimenti inventa robe. Quindi sì, review umana.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-18',
    roomId: 'room-techsafe',
    title: 'Migrare senza flame: monolite → servizi',
    author: 'Stef',
    personaId: 'dev',
    createdAt: hoursAgo(9),
    depth: 2,
    energy: 'costruttivo',
    rootSnippet:
      'Stiamo spezzando un monolite Rails in servizi piccoli. Cosa fare prima per non bruciarci?',
    branches: 5,
    posts: [
      {
        id: 't18-root',
        parentId: null,
        author: 'Stef',
        personaId: 'dev',
        createdAt: hoursAgo(9),
        content:
          'Stiamo spezzando un monolite Rails in servizi piccoli. Prima cosa da fare per non bruciarci?',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't18-r1',
        parentId: 't18-root',
        author: 'Ilaria',
        personaId: 'dev',
        createdAt: hoursAgo(8),
        content:
          'Mappa i bounded context e tira fuori auth e billing per primi. Sono i più dolorosi.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't18-r2',
        parentId: 't18-root',
        author: 'Turi',
        personaId: 'dev',
        createdAt: hoursAgo(7),
        content:
          'Metti un layer di eventi e log centrale prima di staccare pezzi. Senza, il debug diventa inferno.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't18-r3',
        parentId: 't18-r2',
        author: 'Stef',
        personaId: 'dev',
        createdAt: hoursAgo(6),
        content:
          'Log centrale ok. Pensavamo a OpenTelemetry con collector unico.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't18-r4',
        parentId: 't18-root',
        author: 'Marta',
        personaId: 'host',
        createdAt: hoursAgo(5),
        content:
          'Comunica spesso che è un lavoro lungo. Ogni servizio consegnato va celebrato con changelog leggibile.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't18-r5',
        parentId: 't18-r4',
        author: 'Ilaria',
        personaId: 'dev',
        createdAt: hoursAgo(3),
        content:
          'Yes, e tenete i deploy sincronizzati su trunk-based. Le branch lunghe uccidono la migrazione.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-19',
    roomId: 'room-career',
    title: 'Come dite no senza bruciare ponti',
    author: 'Simo',
    personaId: 'deep',
    createdAt: hoursAgo(32),
    depth: 3,
    energy: 'riflessivo',
    rootSnippet:
      'Vorrei imparare a dire no a richieste extra senza sembrare disinteressato.',
    branches: 5,
    posts: [
      {
        id: 't19-root',
        parentId: null,
        author: 'Simo',
        personaId: 'deep',
        createdAt: hoursAgo(32),
        content:
          'Vorrei imparare a dire no a richieste extra senza sembrare disinteressato. Come formulate il rifiuto?',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't19-r1',
        parentId: 't19-root',
        author: 'Paola',
        personaId: 'host',
        createdAt: hoursAgo(29),
        content:
          'Uso “posso farlo, ma significa spostare X a settimana prossima”. Così vedono il costo.',
        waveCount: 5,
        hasWaved: false,
      },
      {
        id: 't19-r2',
        parentId: 't19-root',
        author: 'Luca',
        personaId: 'dev',
        createdAt: hoursAgo(26),
        content:
          'Tengo una lista visibile di priorità approvate. Quando arriva la richiesta in più, chiedo quale togliere.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't19-r3',
        parentId: 't19-r2',
        author: 'Simo',
        personaId: 'deep',
        createdAt: hoursAgo(22),
        content: 'La lista visibile mi manca. La provo in retro team.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't19-r4',
        parentId: 't19-root',
        author: 'Elena',
        personaId: 'deep',
        createdAt: hoursAgo(18),
        content:
          'Scrivo il no anche via mail. Così c’è traccia e non torna come “te lo avevo chiesto”.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't19-r5',
        parentId: 't19-r4',
        author: 'Paola',
        personaId: 'host',
        createdAt: hoursAgo(12),
        content:
          '+1. E chiudi con “fammi sapere se vuoi rivedere insieme le priorità”. Tono calmo.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-20',
    roomId: 'room-career',
    title: 'Settimana tipo per evitare burnout',
    author: 'Claudia',
    personaId: 'host',
    createdAt: hoursAgo(24),
    depth: 2,
    energy: 'costruttivo',
    rootSnippet:
      'Che routine settimanale vi tiene in carreggiata? Cerco esempio realistico.',
    branches: 5,
    posts: [
      {
        id: 't20-root',
        parentId: null,
        author: 'Claudia',
        personaId: 'host',
        createdAt: hoursAgo(24),
        content:
          'Che routine settimanale vi tiene in carreggiata? Cerco esempio realistico, non il solito “alle 5 yoga”.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't20-r1',
        parentId: 't20-root',
        author: 'Marco',
        personaId: 'dev',
        createdAt: hoursAgo(22),
        content:
          'Lunedì pianificazione 30 min, martedì/mercoledì deep work mattina, giovedì meeting, venerdì review + uscita presto.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't20-r2',
        parentId: 't20-root',
        author: 'Anna',
        personaId: 'deep',
        createdAt: hoursAgo(20),
        content:
          'Metto un giorno “no call” fisso e un pomeriggio libero per commissioni. Aiuta la testa.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't20-r3',
        parentId: 't20-r1',
        author: 'Claudia',
        personaId: 'host',
        createdAt: hoursAgo(18),
        content:
          'Meeting al giovedì mi piace. Così lunedì-martedì restano puliti.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't20-r4',
        parentId: 't20-root',
        author: 'Ste',
        personaId: 'creator',
        createdAt: hoursAgo(15),
        content:
          'Blocca anche il pranzo. Se salta, sposti il deep work e ciao ritmo.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't20-r5',
        parentId: 't20-r2',
        author: 'Anna',
        personaId: 'deep',
        createdAt: hoursAgo(9),
        content:
          'Segno la mezza giornata libera come meeting con me stessa. In calendario nessuno osa toccarla.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-21',
    roomId: 'room-career',
    title: 'Cercare un nuovo lavoro senza rumore',
    author: 'Ivy',
    personaId: 'creator',
    createdAt: hoursAgo(13),
    depth: 2,
    energy: 'costruttivo',
    rootSnippet:
      'Sto cercando un nuovo ruolo senza finire nel doomscroll di annunci. Come avete fatto scouting pulito?',
    branches: 5,
    posts: [
      {
        id: 't21-root',
        parentId: null,
        author: 'Ivy',
        personaId: 'creator',
        createdAt: hoursAgo(13),
        content:
          'Sto cercando un nuovo ruolo senza finire nel doomscroll di annunci. Come avete fatto scouting pulito?',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't21-r1',
        parentId: 't21-root',
        author: 'Fede',
        personaId: 'dev',
        createdAt: hoursAgo(12),
        content:
          'Ho fatto shortlist di 15 aziende, contatto diretto su LinkedIn senza feed, solo DM.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't21-r2',
        parentId: 't21-root',
        author: 'Luca',
        personaId: 'dev',
        createdAt: hoursAgo(10),
        content:
          'Aggiorna il CV su Notion e manda link invece di PDF. Puoi aggiornarlo senza rimandare.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't21-r3',
        parentId: 't21-r1',
        author: 'Ivy',
        personaId: 'creator',
        createdAt: hoursAgo(9),
        content:
          'Contatto diretto mi spaventa, ma provo con due aziende piccole.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't21-r4',
        parentId: 't21-root',
        author: 'Mara',
        personaId: 'host',
        createdAt: hoursAgo(7),
        content:
          'Blocca 3 slot a settimana per candidature e chiudi lì. Niente scroll serale.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't21-r5',
        parentId: 't21-r4',
        author: 'Fede',
        personaId: 'dev',
        createdAt: hoursAgo(5),
        content:
          'Yes, e usa un foglio per tracciare follow-up. Così non tieni tutto in testa.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-22',
    roomId: 'room-digital',
    title: 'Weekend senza schermi: come organizzarlo',
    author: 'Noemi',
    personaId: 'deep',
    createdAt: hoursAgo(21),
    depth: 2,
    energy: 'riflessivo',
    rootSnippet:
      'Vorrei provare un weekend senza schermi, ma mi serve un piano pratico per non cedere.',
    branches: 5,
    posts: [
      {
        id: 't22-root',
        parentId: null,
        author: 'Noemi',
        personaId: 'deep',
        createdAt: hoursAgo(21),
        content:
          'Vorrei provare un weekend senza schermi. Mi serve un piano pratico per non cedere dopo 3 ore.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't22-r1',
        parentId: 't22-root',
        author: 'Ale',
        personaId: 'host',
        createdAt: hoursAgo(19),
        content:
          'Metti autoreply su WhatsApp “sono in weekend analogico, rispondo lunedì”. Toglie ansia.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't22-r2',
        parentId: 't22-root',
        author: 'Gianni',
        personaId: 'dev',
        createdAt: hoursAgo(17),
        content:
          'Stampo le mappe e preparo una lista di cose da fare. Se devo cercare info, lo faccio prima.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't22-r3',
        parentId: 't22-root',
        author: 'Mila',
        personaId: 'creator',
        createdAt: hoursAgo(15),
        content:
          'Metto la musica su una vecchia radio e tolgo Alexa. Sembra banale ma cambia.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't22-r4',
        parentId: 't22-r1',
        author: 'Noemi',
        personaId: 'deep',
        createdAt: hoursAgo(12),
        content:
          'Auto-reply fatto. Sto anche avvisando due persone a cui rispondo sempre.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't22-r5',
        parentId: 't22-root',
        author: 'Ale',
        personaId: 'host',
        createdAt: hoursAgo(9),
        content:
          'Bonus: metti in vista un libro corto e una ricetta. Sono ancore quando ti sale il riflesso del telefono.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-23',
    roomId: 'room-digital',
    title: 'Notifiche zero: cosa rimane attivo',
    author: 'Rob',
    personaId: 'dev',
    createdAt: hoursAgo(11),
    depth: 2,
    energy: 'costruttivo',
    rootSnippet:
      'Sto azzerando notifiche. Cosa tenete attivo senza perdere cose importanti?',
    branches: 5,
    posts: [
      {
        id: 't23-root',
        parentId: null,
        author: 'Rob',
        personaId: 'dev',
        createdAt: hoursAgo(11),
        content:
          'Sto azzerando notifiche. Cosa tenete attivo davvero senza perdere cose importanti?',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't23-r1',
        parentId: 't23-root',
        author: 'Cami',
        personaId: 'host',
        createdAt: hoursAgo(10),
        content:
          'Solo chiamate dei “preferiti” e calendario condiviso. Tutto il resto manuale.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't23-r2',
        parentId: 't23-root',
        author: 'Luca',
        personaId: 'dev',
        createdAt: hoursAgo(9),
        content:
          'Email con summary ogni 4 ore. Slack solo menzioni dirette e niente badge.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't23-r3',
        parentId: 't23-r2',
        author: 'Rob',
        personaId: 'dev',
        createdAt: hoursAgo(8),
        content: 'Summary email mi ispira. Che tool usi?',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't23-r4',
        parentId: 't23-root',
        author: 'Elisa',
        personaId: 'creator',
        createdAt: hoursAgo(7),
        content:
          'Modalità focus programmata 3 volte al giorno. Se serve ti chiamano, il resto può aspettare.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't23-r5',
        parentId: 't23-r3',
        author: 'Luca',
        personaId: 'dev',
        createdAt: hoursAgo(6),
        content:
          'Uso SaneBox per filtrare e mail “ritardata” per cose non urgenti. Costa ma vale la calma.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-24',
    roomId: 'room-digital',
    title: 'Social diet: ridurre senza sparire',
    author: 'Giorgia',
    personaId: 'creator',
    createdAt: hoursAgo(5),
    depth: 2,
    energy: 'costruttivo',
    rootSnippet:
      'Sto riducendo i social ma non voglio sparire per chi mi segue: idee pratiche?',
    branches: 5,
    posts: [
      {
        id: 't24-root',
        parentId: null,
        author: 'Giorgia',
        personaId: 'creator',
        createdAt: hoursAgo(5),
        content:
          'Sto riducendo i social ma non voglio sparire per chi mi segue. Come fate una “social diet” senza perdere contatti?',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't24-r1',
        parentId: 't24-root',
        author: 'Teo',
        personaId: 'host',
        createdAt: hoursAgo(4.5),
        content:
          'Programmo 2 post a settimana e rispondo solo in 30 minuti dedicati. Il resto del tempo chiudo l’app.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't24-r2',
        parentId: 't24-root',
        author: 'Marta',
        personaId: 'deep',
        createdAt: hoursAgo(4),
        content:
          'Segnalo in bio: “rispondo il martedì”. Chi resta lo capisce e smette di aspettarsi ansia.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't24-r3',
        parentId: 't24-root',
        author: 'Cris',
        personaId: 'creator',
        createdAt: hoursAgo(3),
        content:
          'Porta il pubblico in una lista email o broadcast. Una volta a settimana e basta.',
        waveCount: 3,
        hasWaved: false,
        attachments: [
          {
            type: 'image',
            url: 'https://images.unsplash.com/photo-1522199710521-72d69614c702?auto=format&fit=crop&w=1200&q=60',
            name: 'newsletter-layout',
          },
        ],
      },
      {
        id: 't24-r4',
        parentId: 't24-r3',
        author: 'Giorgia',
        personaId: 'creator',
        createdAt: hoursAgo(2),
        content:
          'Mail settimanale ok. Posso farla corta con 3 link e basta.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't24-r5',
        parentId: 't24-root',
        author: 'Teo',
        personaId: 'host',
        createdAt: hoursAgo(1),
        content:
          'Se ti senti in colpa, prepara un post “sono in modalità lenta”. Così chi arriva nuovo capisce.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-25',
    roomId: 'room-relations',
    title: 'Discussioni di coppia senza diventare una riunione',
    author: 'Ilaria',
    personaId: 'host',
    createdAt: hoursAgo(27),
    depth: 3,
    energy: 'riflessivo',
    rootSnippet:
      'Come affrontate discussioni di coppia senza checklist infinita?',
    branches: 5,
    posts: [
      {
        id: 't25-root',
        parentId: null,
        author: 'Ilaria',
        personaId: 'host',
        createdAt: hoursAgo(27),
        content:
          'Come affrontate discussioni di coppia senza farle sembrare riunioni di lavoro? Sento che porto la mentalità da ufficio.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't25-r1',
        parentId: 't25-root',
        author: 'Luca',
        personaId: 'dev',
        createdAt: hoursAgo(24),
        content:
          'Abbiamo un “parliamone dopo cena” di 20 minuti, non di più. Timer vero.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't25-r2',
        parentId: 't25-root',
        author: 'Sara',
        personaId: 'deep',
        createdAt: hoursAgo(22),
        content:
          'Usiamo la tecnica “tu parli 5 minuti, io ascolto, poi invertiamo”. Evita interruzioni.',
        waveCount: 4,
        hasWaved: false,
      },
      {
        id: 't25-r3',
        parentId: 't25-r1',
        author: 'Ilaria',
        personaId: 'host',
        createdAt: hoursAgo(19),
        content:
          'Timer mi piace. Mi evita di aprire mille file mentali.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't25-r4',
        parentId: 't25-root',
        author: 'Ale',
        personaId: 'creator',
        createdAt: hoursAgo(15),
        content:
          'Niente telefoni sul tavolo. Solo acqua e blocco note. Se diventa una riunione, stop e riprendi il giorno dopo.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't25-r5',
        parentId: 't25-root',
        author: 'Chiara',
        personaId: 'host',
        createdAt: hoursAgo(9),
        content:
          'Chiudiamo con “ok cosa facciamo domani?” Non tutto va risolto subito, ma almeno un passo.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-26',
    roomId: 'room-relations',
    title: 'Fare amicizia da adulti in città nuove',
    author: 'Diego',
    personaId: 'deep',
    createdAt: hoursAgo(17),
    depth: 2,
    energy: 'riflessivo',
    rootSnippet:
      'Appena trasferito. Idee pratiche per conoscere persone senza eventi forzati?',
    branches: 5,
    posts: [
      {
        id: 't26-root',
        parentId: null,
        author: 'Diego',
        personaId: 'deep',
        createdAt: hoursAgo(17),
        content:
          'Appena trasferito. Idee pratiche per conoscere persone senza eventi forzati?',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't26-r1',
        parentId: 't26-root',
        author: 'Mia',
        personaId: 'host',
        createdAt: hoursAgo(16),
        content:
          'Iscriviti a una palestra piccola o corso di lingua. Vedere le stesse facce ogni settimana aiuta.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't26-r2',
        parentId: 't26-root',
        author: 'Vale',
        personaId: 'creator',
        createdAt: hoursAgo(14),
        content:
          'Faccio coworking 2 giorni a settimana. Non serve parlare molto, basta essere ricorrenti.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't26-r3',
        parentId: 't26-root',
        author: 'Luca',
        personaId: 'dev',
        createdAt: hoursAgo(12),
        content:
          'Offri tu l’organizzazione di un piccolo pranzo dopo il coworking. 3 persone bastano.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't26-r4',
        parentId: 't26-r2',
        author: 'Diego',
        personaId: 'deep',
        createdAt: hoursAgo(10),
        content:
          'Coworking 2 volte a settimana posso farlo. Provo già domani.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't26-r5',
        parentId: 't26-root',
        author: 'Mia',
        personaId: 'host',
        createdAt: hoursAgo(8),
        content:
          'Anche i gruppi di camminata sono ottimi. Poca pressione sociale e puoi staccarti quando vuoi.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
  {
    id: 'thread-27',
    roomId: 'room-relations',
    title: 'Convivenza e divisione dei compiti',
    author: 'Fra',
    personaId: 'host',
    createdAt: hoursAgo(9),
    depth: 2,
    energy: 'costruttivo',
    rootSnippet:
      'Come dividete i compiti in casa senza creare liste infinite?',
    branches: 5,
    posts: [
      {
        id: 't27-root',
        parentId: null,
        author: 'Fra',
        personaId: 'host',
        createdAt: hoursAgo(9),
        content:
          'Come dividete i compiti in casa senza creare liste infinite?',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't27-r1',
        parentId: 't27-root',
        author: 'Ludo',
        personaId: 'creator',
        createdAt: hoursAgo(8),
        content:
          'Abbiamo 4 macro aree: cucina, lavanderia, spesa, pulizie. Ci scambiamo ogni settimana.',
        waveCount: 3,
        hasWaved: false,
      },
      {
        id: 't27-r2',
        parentId: 't27-root',
        author: 'Gio',
        personaId: 'dev',
        createdAt: hoursAgo(7),
        content:
          'Uso un board con sticker. Se resta attaccato per 2 giorni, chiunque lo prende e lo fa.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't27-r3',
        parentId: 't27-r2',
        author: 'Fra',
        personaId: 'host',
        createdAt: hoursAgo(6),
        content:
          'Sticker board sembra meno punitivo di una to-do list. Mi piace.',
        waveCount: 1,
        hasWaved: false,
      },
      {
        id: 't27-r4',
        parentId: 't27-root',
        author: 'Marta',
        personaId: 'deep',
        createdAt: hoursAgo(5),
        content:
          'Facciamo retro mensile di 15 minuti: cosa pesa, cosa funziona. Ribilanciamo lì.',
        waveCount: 2,
        hasWaved: false,
      },
      {
        id: 't27-r5',
        parentId: 't27-r1',
        author: 'Ludo',
        personaId: 'creator',
        createdAt: hoursAgo(3),
        content:
          'E se uno è stressato quella settimana, prende solo 1 area. Scrivilo esplicitamente per evitare rancore.',
        waveCount: 2,
        hasWaved: false,
      },
    ],
  },
];

export const threads = threadData.map(({ posts, ...thread }) => thread);

export const postsByThread = threadData.reduce((acc, { id, posts }) => {
  acc[id] = posts;
  return acc;
}, {});
